
chipone-tddi-objs := cts_driver.o cts_i2c_driver.o cts_spi_driver.o
chipone-tddi-objs += cts_core.o cts_sfctrlv2.o cts_spi_flash.o cts_firmware.o cts_test.o
chipone-tddi-objs += cts_strerror.o
chipone-tddi-objs += cts_charger_detect.o
chipone-tddi-objs += cts_earjack_detect.o
chipone-tddi-objs += cts_platform.o
chipone-tddi-objs += cts_tool.o
chipone-tddi-objs += cts_sysfs.o
chipone-tddi-objs += cts_ioctl.o
chipone-tddi-objs += cts_cdev.o
chipone-tddi-objs += cts_oem.o
obj-m += chipone-tddi.o