#ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
#ccflags-$(CONFIG_MTK_PLATFORM) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
obj-m	+=  device_info.o
