#
# fpsensor_fp.ko
#
# Makefile: for external make invocation
#
# Note:
# - Please refer to modules/sample/Makefile to find out what should be
#   done in this Makefile
#

focaltech_fp-y += ff_ctl.o
focaltech_fp-y += plat-ums9230.o

obj-m += focaltech_fp.o
